<?php

// [mon] comment for now, not needed
add_action('admin_menu', 'fjtg_admin_add_menu_page');

if ( ! function_exists( 'fjtg_admin_add_menu_page' ) ) {
	function fjtg_admin_add_menu_page() {
		add_menu_page(
			'Fujita JSON',
			'Fujita JSON',
			'edit_pages',
			'fjtg_json',
			'fjtg_admin_display_info'
		);
		add_submenu_page(
			'fjtg_json',
			'View Data',
			'View Data',
			'edit_pages',
			'fjtg_json_view_all',
			'fjtg_admin_view_all_json'
		);
		add_submenu_page(
			'fjtg_json',
			'Force Generate',
			'Force Generate',
			'edit_pages',
			'fjtg_json_force',
			'fjtg_admin_force_json'
		);
		// add_submenu_page(
		// 	'fjtg_json',
		// 	'Force CRON',
		// 	'Force CRON',
		// 	'edit_pages',
		// 	'fjtg_json_cron',
		// 	'fjtg_admin_force_cron'
		// );
		// add_submenu_page(
		// 	'fjtg_json',
		// 	'Delete Subsite',
		// 	'Delete Subsite',
		// 	'edit_pages',
		// 	'fjtg_json_delete_subsite_json',
		// 	'fjtg_admin_delete_subsite_json'
		// );
	}
}

if ( ! function_exists( 'fjtg_admin_display_info' ) ) {
	function fjtg_admin_display_info() { ?>
		<div class="wrap">
			<h1>Fujita JSON</h1>
			<p>
				Fujita Group runs mainly on flat files to optimize loading of data from Wordpress. <br/>
				This section is mainly made for developers to optimize, debug, and verify data.
			</p>
			<hr/>
			<h2>
				View JSON
				<a href="<?php echo admin_url( 'admin.php?page=fjtg_json_view_all', 'http' ) ?>"
					class="page-title-action">
					View
				</a>
			</h2>
			<p>This is a page to view the JSON flat files.</p>
			<hr/>
			<h2>
				Force Generate
				<a href="<?php echo admin_url( 'admin.php?page=fjtg_json_force', 'http' ); ?>"
					class="page-title-action">
					Force Now
				</a>
			</h2>
			<p>
				Force generation of all JSON files is to force the system to regenerate all JSON flat files. <br/>
				On a daily basis, JSON files would be automatically update when there is an add/update/delete of any post within the system.
			</p>
			<hr/>
			<h2>
				Delete Subsite JSON
				<a href="<?php echo admin_url( 'admin.php?page=fjtg_json_delete_subsite_json', 'http' ) ?>" class="page-title-action">Delete Now</a>
			</h2>
			<p>
				This is a page to delete all Subsite related JSON files.<br/>
			</p>
		</div>
	<?php
	}
}

if ( ! function_exists( 'fjtg_admin_force_json' ) ) {
	function fjtg_admin_force_json() {

		$hotel_dir = rojak_get_json_site_dir('per-hotel');

		foreach( glob( $hotel_dir . '*' ) as $file) {
			if ( is_file( $file ) ) {
				unlink( $file );
			}
		}

		fjtg_admin_generate_per_hotel();

		$hotel_list          = fjtg_json_generate_hotel_list( true );
		$hotel_list          = json_encode( $hotel_list, JSON_PRETTY_PRINT );
		$hotel_list_filename = fjtg_get_site_json_filenames( 'posts-hotel' );

		fjtg_json_generate_hotel_list_minimal();

		//================ page render =================//

		$base_dir  = rojak_get_json_site_dir();
		$force_url = admin_url( 'admin.php?page=fjtg_json_force', 'http' );
		echo <<<HTML
			<div class="wrap">
				<h1>
					Force JSON
					<a href="$force_url" class="page-title-action">Force Again</a>
				</h1>
				<p>
					This is a page to force the system to generate all JSON flat files. <br/>
					On a daily basis, JSON files would be automatically updated whenever an add/update/delete happens on any post or page within the system.
				</p>
				<hr/>
				<h2>$hotel_list_filename</h2>
				<p>DIR: <code>$base_dir</code></p>
				<p>This JSON file is generated by getting all individual Hotel JSON files located in <br/>
					<code>$hotel_dir</code></p>
				<textarea name="json" readonly="true" rows="30" placeholder="" wrap="on" style="word-wrap: normal;overflow-x: scroll; width: 95%; font-family: Consolas, Courier, monospace; font-size: 13px; ">$hotel_list</textarea>
			</div>
HTML;
	}
}

if ( ! function_exists( 'fjtg_admin_force_cron' ) ) {
	function fjtg_admin_force_cron() {

		//================ page render =================//
		$iframe_url = get_bloginfo( 'url' ) . '/wp-content/fjtg-cron/';
		$force_url = admin_url( 'admin.php?page=fjtg_json_cron', 'http' );
		echo <<<HTML
			<div class="wrap">
				<h1>
					Force CRON
					<a href="$force_url" class="page-title-action">Run CRON Again</a>
				</h1>
				<p>
					This is a page to force the system to run CRON.<br/>
					On a daily basis, CRON would run hourly.
				</p>
				<hr/>
				<p>URL: <code>$iframe_url</code></p>
				<iframe src="$iframe_url" style="width: 95%; height: 800px"></iframe>
			</div>
HTML;
	}
}


if ( ! function_exists( 'fjtg_admin_view_all_json' ) ) {
	function fjtg_admin_view_all_json() {

		//================ page render =================//
		$refresh_url = admin_url( 'admin.php?page=fjtg_json_view_all', 'http' );
		echo <<<HTML
			<div class="wrap">
				<h1>
					View JSON
					<a href="$refresh_url" class="page-title-action">Refresh</a>
				</h1>
				<p>This is a page to view the JSON flat files.</p>
				<hr/>
			</div>
HTML;

		fjtg_admin_view_json( 'posts-hotel' );
		fjtg_admin_view_json( 'posts-city' );
		fjtg_admin_view_json( 'posts-brand' );

	}
}

if ( ! function_exists( 'fjtg_admin_view_json' ) ) {
	function fjtg_admin_view_json( $filename ) {
		$data = fjtg_json_get_posts( $filename );
		$data = json_encode( $data, JSON_PRETTY_PRINT );
		$data_filename = fjtg_get_site_json_filenames( $filename );
		echo <<<HTML
			<div class="wrap">
				<h2>$data_filename</h2>
				<textarea name="json" readonly="true" rows="25" placeholder="" wrap="on" style="word-wrap: normal;overflow-x: scroll; width: 95%; font-family: Consolas, Courier, monospace; font-size: 13px; ">$data</textarea>
				<hr/>
			</div>
HTML;
	}
}

if ( ! function_exists( 'fjtg_admin_generate_per_hotel' ) ) {
	function fjtg_admin_generate_per_hotel() {
		$count = 0;
		$hotels_data = array();
		$args=array(
			'post_type'        => 'hotel',
			'posts_per_page'   => -1,
			'post_status'      => 'publish',
			'suppress_filters' => 0
		);
		$hotel_posts = new WP_Query($args);
		if ( $hotel_posts->have_posts() ) {
			while ( $hotel_posts->have_posts() ) { $hotel_posts->the_post();

				if ( ! empty( $hotel_posts->post->post_name ) &&
				     ! ctype_digit( $hotel_posts->post->post_name ) ) {

					// delete json first
					fjtg_hotel_delete_json( $hotel_posts->post->post_name );

					// generate json again
					$hotels_data[$count] = fjtg_json_get_post_hotel( $hotel_posts->post->post_name );

					// just increase count, nothing much :3
					$count++;
				}

			}
		}
		wp_reset_query();
	}
}


// if ( ! function_exists( 'fjtg_admin_delete_subsite_json' ) ) {
// 	function fjtg_admin_delete_subsite_json() {
// 		$json_dir = rojak_get_json_root_dir();
// 		$files = array_filter( glob( $json_dir . '*/*.json' ), function($v) {
// 			$json_dir = rojak_get_json_root_dir();
// 			if ( rojak_str_contains( $v, $json_dir . '1-per-hotel/' ) ||
// 			     rojak_str_contains( $v, $json_dir . '1/' ) ) {
// 				return false;
// 			}
// 			return $v;
// 		});

// 		foreach( $files as $file ) {
// 		  if( is_file( $file ) )
// 		    unlink( $file ); // delete file
// 		}

// 		$files_pretty = array();
// 		foreach( $files as $file ) {
// 			$files_pretty[] = str_replace( $json_dir, '', $file);
// 		}
// 		$files_pretty = print_r( $files_pretty, true );

// 		$delete_json_url = admin_url( 'admin.php?page=fjtg_json_delete_subsite_json', 'http' );
// 		echo <<<HTML
// 			<div class="wrap">
// 				<h1>
// 					Delete Subsite JSON
// 					<a href="$delete_json_url" class="page-title-action">Delete Again</a>
// 				</h1>
// 				<p>
// 					This is a page to delete all Subsite related JSON files.<br/>
// 				</p>
// 				<hr/>
// 				<p>Files delete in <code>$json_dir</code></p>
// 				<textarea name="json" readonly="true" rows="30" placeholder="" wrap="on" style="word-wrap: normal;overflow-x: scroll; width: 95%; font-family: Consolas, Courier, monospace; font-size: 13px; ">$files_pretty</textarea>
// 			</div>
// HTML;
// 	}
// }
